
#pragma once
#include "git/common.h"

namespace cultlang {
namespace git 
{
  extern ::craft::lisp::BuiltinModuleDescription BuiltinGit;

  CULTLANG_GIT_EXPORTED ::craft::instance<::craft::lisp::Module> make_bindings(::craft::instance<::craft::lisp::Namespace> ns, ::craft::instance<> loader);


}}

CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_attr_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_blame_flag_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_branch_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_cert_ssh_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_cert_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_clone_local_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_checkout_strategy_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_config_level_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_credtype_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_cvar_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_delta_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_describe_strategy_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_binary_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_find_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_flag_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_format_email_flags_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_format_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_line_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_option_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_diff_stats_format_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_direction)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_error_code)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_feature_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_filemode_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_filter_flag_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_filter_mode_t)
//CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_hashsig_option_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_idxentry_extended_flag_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_index_add_option_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_indexcap_t)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_indxentry_flag_t)

CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_repository)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_oid)

CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_commit)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_tree)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_tree_entry)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_blob)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_tag)
CRAFT_TYPE_DECLARE(CULTLANG_GIT_EXPORTED, git_signature)

